# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'vs2017-win2016'

pr:
  paths:
    exclude:
    - README.md

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'build'

- script: |
    cd $(Build.BinariesDirectory)
    ls

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/'
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'artifact $(Build.BuildId)'
    targetPath: 'dist/'

- task: AzureRmWebAppDeployment@4
  inputs:
    connectionType: PublishProfile
    publishProfilePath: '/test-20181126.pubxml'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    publishProfilePassword : 'rPik39XQa9lJFuCSctuStH7ja3k8NzoSAshHejwKAofku6pmduyBF3kYx8BW'
    appType: 'webApp'